import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const scriptFilePath = fileURLToPath(import.meta.url);
const scriptDir = path.dirname(scriptFilePath);
const projectRoot = path.resolve(scriptDir, "..");
const envPath = path.join(projectRoot, ".env");
const envExamplePath = path.join(projectRoot, ".env.example");
const isHostedMode = process.argv.includes("--hosted");

function run(command, args, options = {}) {
  const printable = `${command} ${args.join(" ")}`;
  console.log(`\n> ${printable}`);

  const result = spawnSync(command, args, {
    stdio: "inherit",
    shell: process.platform === "win32",
    cwd: projectRoot,
    ...options,
  });

  if (result.status !== 0) {
    throw new Error(`Command failed: ${printable}`);
  }
}

function commandExists(command, args = ["--version"]) {
  const result = spawnSync(command, args, {
    stdio: "ignore",
    shell: process.platform === "win32",
    cwd: projectRoot,
  });

  return result.status === 0;
}

function dockerComposeUp() {
  // Try modern Docker Compose first.
  try {
    run("docker", ["compose", "up", "-d"]);
    return;
  } catch {
    // Fallback to legacy docker-compose.
    run("docker-compose", ["up", "-d"]);
  }
}

function printDockerMissingHelp() {
  console.error("\nDocker setup not available on this machine.");
  console.error("Use one of these options:");
  console.error("1) Install Docker Desktop, then run: npm run setup");
  console.error("2) Use hosted database mode:");
  console.error(
    "   PowerShell: $env:SETUP_DATABASE_URL=\"postgresql://USER:PASSWORD@HOST:5432/DB_NAME?sslmode=require\""
  );
  console.error("   Then run: npm run setup:hosted");
}

function buildHostedEnvText(databaseUrl) {
  return [
    "# Auto-generated by scripts/setup.mjs (hosted mode)",
    `DATABASE_URL=${databaseUrl}`,
    "JWT_SECRET=dev-secret-change-me",
    "PORT=4000",
    "NODE_ENV=development",
    "ADMIN_REGISTRATION_CODE=dev-admin-register-code",
    "ALLOWED_ORIGINS=",
    "GOOGLE_MAPS_API_KEY=",
    "LOG_LEVEL=info",
    "",
  ].join("\n");
}

function ensureEnvFile() {
  if (fs.existsSync(envPath)) {
    console.log(".env already exists; keeping existing values.");
    return;
  }

  if (isHostedMode) {
    const hostedUrl = process.env.SETUP_DATABASE_URL || process.env.DATABASE_URL;

    if (!hostedUrl) {
      throw new Error(
        "Hosted mode selected but DB URL missing. Set SETUP_DATABASE_URL (recommended) or DATABASE_URL before running setup."
      );
    }

    fs.writeFileSync(envPath, buildHostedEnvText(hostedUrl), "utf8");
    console.log("Created .env for hosted database.");
    return;
  }

  if (fs.existsSync(envExamplePath)) {
    fs.copyFileSync(envExamplePath, envPath);
    console.log("Created .env from .env.example.");
    return;
  }

  throw new Error("Missing both .env and .env.example. Cannot continue setup.");
}

function main() {
  console.log("Starting automated backend setup...");
  console.log(`Project root: ${projectRoot}`);

  ensureEnvFile();

  run("npm", ["install"]);

  if (!isHostedMode) {
    if (!commandExists("docker", ["compose", "version"]) && !commandExists("docker-compose", ["--version"])) {
      printDockerMissingHelp();
      process.exit(1);
    }

    dockerComposeUp();
  }

  run("npx", ["prisma", "generate"]);
  run("npx", ["prisma", "migrate", "deploy"]);
  run("npx", ["prisma", "db", "seed"]);

  console.log("\nSetup complete.");
  console.log("Run 'npm run dev' to start backend.");
}

try {
  main();
} catch (error) {
  console.error("\nSetup failed:");
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
}
