ALTER TABLE "AgentProfile"
ADD COLUMN IF NOT EXISTS "ratingSum" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "ratingCount" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "AgentTransaction"
ADD COLUMN IF NOT EXISTS "userRating" INTEGER,
ADD COLUMN IF NOT EXISTS "ratedAt" TIMESTAMP(3);
